### ISSUE TITLE
Question: How to retrieve local path for called DLL

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#100]
I tried to load a DLL which is located outside of a test app's folder:

project/tests/testapp.bmx
project/mydll.dll
project/otherdll.dll

now this mydll.dll file itself tries to load another dll - it would do this by `LoadLibraryW("otherdll.dll")`.
But as testapp.bmx is located in another folder, the "CurrentDir" (or CWD) will be "project/test". While it succesfully can call `LoadLibraryW("../mydll.dll")` (as it knows where its DLL of interest is located) the now loaded mydll.dll will not find otherdll.dll as the current working directory is still "project/test".

How can "mydll.dll" find out where it is located? RealPath wants an URI - but I do not have it.

**Comment by woollybah** [comment]
I've made some changes which allow you to use AppFile and AppDir inside the DLL to retrieve the location of the DLL.
Hope this helps ;-)
