### ISSUE TITLE
[Win32] Application icon not set for window

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#102]
While a corresponding "sourcefile.ico" is inserted into the application and correctly shown in the "file explorer", the opened window of the application does only show a default icon.

![img](http://i.imgur.com/TjiOvQf.png)
I also tried this old code here:
```
	'set the icon of the app
	Function SetIcon(iconname$, TheWindow%)
		Local icon:Int=ExtractIconA(TheWindow,iconname,0)
		Local WM_SETICON:Int = $80
		Local ICON_SMALL:Int = 0
		Local ICON_BIG:Int = 1
		sendmessage(TheWindow, WM_SETICON, ICON_BIG, icon)
	End Function

	Extern "win32"
		Function ExtractIconA%(hWnd%,File$z,Index%)
		Function GetActiveWindow%()
		Function SendMessage:Int(hWnd:Int,MSG:Int,wParam:Int,lParam:Int) = "SendMessageA@16"
	End Extern

	SetIcon(AppFile, GetActiveWindow())
```
Resulting in the same default ("white window") icon.

**Comment by woollybah** [comment]
I tested this commit for both gl and dx, with, and without a supplied icon, and it seems to work okay - falling back to the standard if no icon is provided.

I dunno if we want to be injecting a "BlitzMax" icon if the user doesn't supply one themselves?
