### ISSUE TITLE
Windows, Changed GC finalizer commit = Exception Access Violation..?

### ISSUE THREAD

**Issue by olejr** [bmx-ng/brl.mod#106]
When there's nothing to do for **bmk makemods**, Windows throw an EXCEPTION_ACCESS_VIOLATION.
Started after the changes to GC finalizer(cf296b58aabee5345d7f5b6066f5432b25751c82). Atleast  commit 07d5b8e14617135c4f09b647cbb485ad95162dc1 have no such issue.

This is after rebuilding modules, then (latest) bmk/bcc, and then rebuild modules on Windows 10 x64.

**Comment by woollybah** [comment]
I have fixed two issues, both of which appeared running an x64 bmk in gdb on Windows. One was a 64-bit mis-allocation issue, the other was GC related.

Hopefully that will solve your problems?

Although the GC changes are currently being a nuisance (pretty much everywhere), they are the best settings for guaranteeing collection of everything that should be collected. It's just a case of fixing the bugs now...
So apologies for the ongoing problems.

**Comment by olejr** [comment]
This problem solved thank you.
