### ISSUE TITLE
Cannot use SDL.GLSDLMax2D and BRL.TimerDefault together?

### ISSUE THREAD

**Issue by wombatswaffles** [bmx-ng/brl.mod#110]
Using both SDL.GLSDLMax2D and BRL.TimerDefault results in **Unhandled Exception:Cannot initialise MacOSSystemDriver . System driver already configured as SDLSystemDriver**.

```
Framework SDL.GLSDLMax2D
Import BRL.TimerDefault

Graphics 640, 480, 32
Repeat
	Cls
	DrawText(String(MouseX()) + ", " + String(MouseY()), 32, 32)
	DrawRect(MouseX(), MouseY(), 64, 64)
	Flip
Until KeyHit(KEY_ESCAPE)```

**Comment by GWRon** [comment]
You have to use the `sdl.SDLTimer` module (as "somehow" stated in the other issue already).

**Comment by wombatswaffles** [comment]
I was using Framework, but the post didn't show it because it had that line next to the ``` for a code block.

Ah, I did not see about SDL.SDLTimer. I had no idea it existed. All is working fine now.

Thank you for your help!

**Comment by GWRon** [comment]
Yes ... do not write code after the three ticks - but place a "blitzmax" there and get color highlighting ;-)

"```"Blitzmax

```BlitzMax
Framework SDL.GLSDLMax2D
Import SDL.SDLTimer

Graphics 640, 480, 32
Repeat
	Cls
	DrawText(String(MouseX()) + ", " + String(MouseY()), 32, 32)
	DrawRect(MouseX(), MouseY(), 64, 64)
	Flip
Until KeyHit(KEY_ESCAPE)
```

**Comment by wombatswaffles** [comment]
That's good to know. 👍 Thanks.
