### ISSUE TITLE
Use of compilerswitch "?disabled"

### ISSUE THREAD

**Issue by Octav14n** [bmx-ng/brl.mod#13]
The compiler condition `?disabled` is used in directx related modules in brl.mod and pub.mod.
what is this used for?
Can we just delete those lines included in it?

bcc_ng build in debug mode DebugStops at every occurrence of it.

```Bash
bmax/mod$ grep -R -nr -i "?disable"
brl.mod/d3d9max2d.mod/d3d9max2d.bmx:18:?disabled
brl.mod/dxgraphics.mod/dxgraphics.bmx:73:?disabled
brl.mod/d3d7max2d.mod/d3d7max2d.bmx:62:?disabled
pub.mod/directx.mod/directx.bmx:28:?disabled
pub.mod/directx.mod/dsound.bmx:69:?disabled
```

**Comment by GWRon** [comment]
Maybe it was used before ?bmxng was introduced ... because vanilla defaults to "false" on unknowm conditionals.

Am 5. März 2015 18:25:50 MEZ, schrieb Simon K <notifications@github.com>:

**Comment by woollybah** [comment]
```?disabled``` is just a no-op compiler flag so that some blocks of code are ignored - because currently the dx stuff doesn't work.
Obviously it shouldn't stop on debug there...

**Comment by woollybah** [comment]
Patched bcc to not debugstop on errors.
