### ISSUE TITLE
brl.mod/vector.mod

### ISSUE THREAD

**Issue by xlsior75** [bmx-ng/brl.mod#139]
Windows, latest NG bmk/bcc:

[  4%] Processing:vector.bmx
Compile Error: Cyclic declaration of 'SVec2D'.
[c:/code/BlitzmaxNG810/mod/brl.mod/vector.mod/vector.bmx;51;0]
Build Error: failed to compile (-1) c:/code/BlitzmaxNG810/mod/brl.mod/vector.mod/vector.bmx

**Comment by HurryStarfish** [comment]
Duplicate of bmx-ng/bcc/issues/453
