### ISSUE TITLE
TSocket bugging out after GCCollect()

### ISSUE THREAD

**Issue by Hezkore** [bmx-ng/brl.mod#148]
Sadly, I can't provide an example of this right now.
But it seems as if TSocket stops working after a GCCollect.

I'm basically just doing what this example tells me to do: [https://www.blitzmax.org/docs/en/tutorials/tcp_tutorial/#receiving-data](https://www.blitzmax.org/docs/en/tutorials/tcp_tutorial/#receiving-data)
But inside a While True loop.
```BlitzMax
'Connect code here
GCSetMode( 1 )
While True
	GCCollect()
	Delay( 1000 )
Wend
End
```
And after a while TSocket seems to just... die...
When I stop the GCCollector TSocket works, all the time.
But then when I call GCCollect TSocket dies.
The debugger doesn't even spit out any message or anything, the application just ends.
Sometimes TSocket just stops working instead of the application ending, no error or anything, it just doesn't receive or send any data.
It seems to be related to sending data, as that's what I'm doing right after connection.

UPDATE:
It seems to be related to me creating a static bank from what the Socket returns.
```
Local buf:Byte Ptr[avail]
Local dataLen:Size_T = _socket.Recv(buf, avail )
If dataLen Then TBank.CreateStatic( buf, dataLen )
```

**Comment by woollybah** [comment]
A static bank relies on the buffer not to be GC'd before the bank has finished using it. In your short example above, `buf` is local. Your bank therefore is limited to the lifetime of that local variable.

When you pass a pointer to the data within an array, you are not passing a reference to the array - and therefore the array can be collected whenever the array itself goes out of scope.

I could add an overloaded CreateStatic that takes a Byte array directly, and holds a reference to the array object within the bank. That would resolve the issue of miss-using CreateStatic.
