### ISSUE TITLE
Seek() + WriteLine() in streams creating garbage

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#15]
The following code creates a file "ng_logger.txt". The expected output is
```
Header
line0
line1
...
line10
```
But instead it consists of 0-bytes and the last line:
![ghex](https://cloud.githubusercontent.com/assets/2625226/6747527/eb65999e-ceda-11e4-869e-99c92ce912b3.png)

```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import Brl.Retro


Global fileName:String = "ng_logger.txt"
Global headerWritten:Int = False
For Local i:Int = 0 To 10
	Local size:Int = FileSize(filename)
	If size = -1
		Print "file missing. creating ..." 
		If Not CreateFile(filename)
			Throw "Cannot create logfile: "+filename
		EndIf
	EndIf
	Local file:TStream = WriteFile(filename)

	If Not headerWritten
		WriteLine(file, "Header")
		headerWritten = True
	'if we already have written the header, move to the end of
	'the file
	Else
		'the problematic part ?
		file.Seek(size)
	EndIf
	WriteLine(file, "line"+i)

	CloseFile(file)
Next
```

"Seek" seems to correctly move the position. BUT ... when not using "seek" (eg only doing "header" + "line0" it is correctly stored in the file).

**Comment by GWRon** [comment]
This sample is even shorter (but still failing to create a proper file):

```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import Brl.Retro


Global fileName:String = "ng_logger.txt"
For Local i:Int = 1 To 9
	Local size:Int = FileSize(fileName)
	If size = -1 And Not Not CreateFile(fileName) Then Throw "Cannot create file: "+fileName

	Local file:TStream = WriteFile(filename)
	If i > 1 Then file.Seek(size) 'append after first line...
	
	WriteLine(file, "line"+i)

	CloseFile(file)

	size = FileSize(fileName)
	'7 = 5 bytes for "lineX" + 2 bytes lineending
	Print "filesize: " + FileSize(fileName) + " (should be " + (i*7) + ")."
Next
```

On my computer the filesize is "correct", but instead of nice alphanumeric chars I get these "nulls".

**Comment by woollybah** [comment]
Not Not is True.

**Comment by GWRon** [comment]
Yes -- introduced that by making the sample, but it fails with or without (as for me the file already exists - and in that case the file is not created - but still file pointer is at offset 0... ).

Adjusted sample

**Comment by woollybah** [comment]
Are you expecting to be able to append to the end of the file? Then your use of ```WriteFile``` is wrong. You should be using ```OpenFile```.

**Comment by GWRon** [comment]
As it works with vanilla, I assume I am doing it right.

WriteFile opens a file to write in it, using "seek" allows to move in the then existing stream.

**Comment by woollybah** [comment]
It doesn't work for me in legacy... it has the same problem as you are seeing in ng.

**Comment by woollybah** [comment]
The file needs to be opened with ```r+b``` for appending to work, that is only enabled with readable and writeable are True.

**Comment by GWRon** [comment]
I will check then when returning home ... it fails in my logger class (which does the same) so maybe I missed a step there... thanks for clarification.

Will close the bug if the error is on my side :laughing:

**Comment by GWRon** [comment]
You are right ... my original implementation was faulty already - but was corrected automatically upon app end (because I dumped my log then again - creating a new file and printing everything in one turn).

Works as expected with "OpenFile".

**Comment by woollybah** [comment]
Glad we are getting your bugs fixed :-)

**Comment by GWRon** [comment]
This is why you are doing it... isnt it? :hamster:
