### ISSUE TITLE
[brl.xml] Saving a just loaded XML is truncated

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#154]
Example files: https://raw.githubusercontent.com/TVTower/TVTower/master/res/database/Default/database_news.xml
https://raw.githubusercontent.com/TVTower/TVTower/master/res/database/Default/database_ads.xml
https://raw.githubusercontent.com/TVTower/TVTower/master/res/database/Default/database_programmes.xml

```BlitzMax
SuperStrict
Framework Brl.xml
Import Brl.StandardIO

'result "-1"
'Local doc:TxmlDoc = TxmlDoc.parseFile("database_news.xml")
'print "save result: " + doc.SaveFile("-")

'result "-1"
Local doc:TxmlDoc = TxmlDoc.parseFile("database_ads.xml")
print "save result: " + doc.SaveFile("-")

'result "0"
Local doc:TxmlDoc = TxmlDoc.parseFile("database_ads.xml")
print "save result: " + doc.SaveFile("test.xml")

```
Both print only a ~16k long portion of the xml file and then the save result is "-1".
When saving to a file then the result is 0 (which means "successful") but it is still truncated.

Interesting: the "ads" becomes 16.4kb, the "news" becomes 32.8kb (so exactly 2x). But this seems to be just a coincidence. Saving "programmes" it cuts at 344.1kb (originally 588.3kb).

Removing some data from inbetween the "raw data" leads to the same exported size (so it achieves to export some more nodes).

**Comment by GWRon** [comment]
If I iterated over the children of the `doc` (`TXmlNode(doc._nodeptr).GetChildren()` etc.) then it lists all the entries (and in my game they are also loaded successfully). So I think the mxml_*-commands when saving a node somehow stumble over something.

**Comment by GWRon** [comment]
I have a strong suspicion...

I added some debug prints to "mxml_file.c" to print out element types, element names, attribute count, ... during `mxml_write_node()`.

And when does it stop doing stuff?
```
node "Tu-doch-so"    type = 2
node "
				"    type = 2
node "!-- <en>Fakation</en> --"    type = 6
```

Oh, it stops when it reaches `<!-- <en>Fakation</en> -->` ... removing these comments from the one file (which only two of them) and it wrote all 212 ads.

So ... somehow it stumbles over the "comments" - either marked wrongly or codewise. Will have to check further

**Comment by GWRon** [comment]
Seems 2dda7d15f324b383a274d2e8d44f034ac2053883#diff-95d87c01e3b2db4c3bff3e9bc8dba392 introduced this behaviour.

Once this was found out ... append the MXML_COMMENT to:
```C
  for (current = node; current; current = next)
  {
   /*
    * Print the node value...
    */

    switch (current->type)
    {
      case MXML_ELEMENT :
```

so it becomes
```C
```C
  for (current = node; current; current = next)
  {
   /*
    * Print the node value...
    */

    switch (current->type)
    {
      case MXML_ELEMENT :
      case MXML_COMMENT :
```
et voila ... works.

**Comment by GWRon** [comment]
@woollybah 
If it is ok to fix it that way I would happily create a Pull Request for it - or you tell me the desired adjustments (eg copy-pasting the code and handling the "MXML_COMMENT" separately.

**Comment by woollybah** [comment]
Yes, that looks fine. Thanks.
