### ISSUE TITLE
DrawCommands require floats, Math commands return Doubles

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#158]
I often use commands like this:
```
SetScale sin(Millisecs()/5), sin(Millisecs()/5)
```
NG would error out (except with the optional flag to make them warnings) as `sin()` returns a `double` while `SetScale()` expects `floats`.

So it would be nice to have:
ceilF(), floorF(), sinF(), cosF(), tanF(), maxF, minF, ... and so on.
Maybe the "I" variants for integers could be interesting too.

I would like to avoid these functions using their double-counterparts and just doing the cast "there" instead of the users blitzmax code.

Brucey also suggested to overload the graphic commands (SetScale, DrawImage, DrawSubImageRect ....) to allow various parameter types so you would then not need to use "ceilF()" - of course that means that all given parameters would then need this parameter type ("all coordinates of type float")

**Comment by woollybah** [comment]
Okay... so I've implemented overloads for the drawing commands.

For Float based math functions, I've currently got overloaded versions -
```blitzmax
Function Sin:Double( x:Double )="bbSin"

Function Sin:Float( x:Float )="bbSinf"
```
I could make them have an `F` suffix, but I don't think it's entirely necessary. Depending on your source value, the compiler chooses the appropriate function. For example, for an `Int` argument, it prefers the Float based `Sin`.

Presumably, you'd generally have your arguments of the correct type to begin with.

**Comment by HurryStarfish** [comment]
This seems very dangerous to me.
Any existing code of the form `Local result:Double = Sin(5)` (probably a *lot*, especially considering these functions work with degree angles) will now behave differently than before. Existing code will compile without warnings, yet calculations will produce less precise results.
And even in new code, the programmer must now be extremely careful to always call these functions with the right parameter types, or they will silently introduce subtle rounding errors into calculations.

I think these functions are better off without overloads.
If code like `SetScale Sin(x), Sin(y)` produces warnings, then it's `SetScale` which should get an overload... or you could write `SetScale Float Sin(x), Float Sin(y)` instead, making the loss of precision explicit.

**Comment by GWRon** [comment]
I am with @HurryStarfish here: having overloaded basic functions like `sin()` is dangerous. Of course it was not aware to me until our beloved Starfish chimed in to warn ;)

@HurryStarfish 
You proposed overloaded `SetScale` - I already wrote about it in my initial post. What happens to
`SetScale(Sin(x), myFloatValue)` - first is a `Double` and second a `Float`. This means you needed overloads for each combination - whch is to avoid I think.

It would work for integers `SetScale(Sin(x), myIntValue)` and overloads accepting `SetScale(Double, Double)` as integers fit into and newer BCC no longer complains.

**Comment by HurryStarfish** [comment]
> What happens to SetScale(Sin(x), myFloatValue) - first is a Double and second a Float. This means you needed overloads for each combination - whch is to avoid I think

That one should work without a warning, since a `Double` can hold any value a `Float` can. `Float` -> `Double` is a lossless conversion but `Double` -> `Float` isn't, so it'll choose the `Double` overload for mixed arguments.

Although personally, I think casting isn't a big deal either. I wouldn't mind having no overloads and just having to write `SetScale(Float Sin(x), myFloatValue)` in general. Graphics drawing code doesn't tend to be the most terse and beautiful code anyway :)

**Comment by GWRon** [comment]
Having casts can lead to odd behaviour if the underlying function or variable changes the actual type. Code would still compile then whole actual behaviour could change.


Setscale expects two floats... If I pass a float and a double then at least in older BCCs the cast from float to double (if there was a double-overloaded setScale) was imho requiring a manual cast to avoid an error message. Newer ones do no longer have that issue... So you are right about that.

**Comment by HurryStarfish** [comment]
> Having casts can lead to odd behaviour if the underlying function or variable changes the actual type. Code would still compile then whole actual behaviour could change.

Hmm, I'm not sure what exactly you're referring to by that. Could you give an example?
There is certainly still [this bug](/bmx-ng/bcc/issues/277), which can lead to weird behaviour in certain situations...
