### ISSUE TITLE
Brl.SystemDefault only handles 3 Mouse buttons

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#159]
```C
    case WM_LBUTTONDOWN:case WM_RBUTTONDOWN:case WM_MBUTTONDOWN:
        SetCapture( hwnd );
        id=BBEVENT_MOUSEDOWN;
        data=(msg==WM_LBUTTONDOWN) ? 1 : (msg==WM_RBUTTONDOWN ? 2 : 3);
        x=(short)LOWORD(lp);
        y=(short)HIWORD(lp);
        break;
```

So any 4th or 5th mouse button (Eg page navigation support) is ignored - or in my case returns either "0" in the event data, or "1" (so equals nothing or first mouse button).

**Comment by woollybah** [comment]
I don't have a way to handle the two extra button on macOS yet.
