### ISSUE TITLE
Reflection: Metadata gone missing

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#16]
I cannot explain it exactly - and even more, cannot give a (non) working example.

- I expose objects/methods/functions/properties to LUA using reflection
- I limit this expose via metadata 
- {_exposeToLua} -> expose everything below
- {_exposeToLua="selected"} -> expose everything having its own {_exposeToLua}-meta-data

Now my app with NG blames that the lua scripts try to call methods _not_ exposed. In vanilla they are happily exposed - and accessible.
I tried to make it reproduceable in a small example using the same logic (function stripped down a bit), but there... it just worked.

Is there a chance that the "complexity" of my bigger project creates the hassle? (compared to a small single-file-sample just having a handful of types and extends).

I checked the "metadata" of the object in my engine - and they seems to be empty in the failing-cases (compiled with NG, in vanilla they are "filled").

Ideas how to narrow it down?

LuaEngine:
https://github.com/GWRon/Dig/blob/master/base.util.luaengine.bmx
"Filtering" is done in "TLuaEngine.Index()"

Like said, If I copy this code and use it in a simple example, with some simple classes, it just "works" as expected... 
Also this portion is not encapsulated as I wanted it to be - so the problematic portion is in the "main"-file which includes many things and the resulting c-file is 2.8mb in release or 6.7mb in debug ...so not that small). This makes it really hard to strip down the whole project for narrowing down the source of the flaw.

**Comment by woollybah** [comment]
I'd check the generated .i files, and see if the metadata is missing from there?
If it is missing, then there's an issue with bcc not writing it out properly.
If it is there, perhaps there's an issue with bcc reading it in properly...

Or something else.

**Comment by woollybah** [comment]
My mistake, it's in the generated C source, not the .i

**Comment by GWRon** [comment]
Where is that meta data printed in the .i-file?

**Comment by GWRon** [comment]
Ahh think I got it ...

```BlitzMax
Type TPlayerBase {_exposeToLua="selected"}
	'attention: when used through LUA without param, the param gets "0"
	'instead of "-1"
	Method GetMoney:Int(day:Int=-1) {_exposeToLua}
		Return 0
	End Method
End Type

Type TPlayer extends TPlayerBase {_exposeToLua="selected"}
	'overridden
	Method GetMoney:Int(day:Int=-1) {_exposeToLua}
		print "getmoney called"
		Return GetFinance(day).money
	End Method
End Type
```

The problem is that I have overriden "GetMoney", "GetProgrammePlan" is only existent in "TPlayer". So the Metadata is missing as soon as it gets defined multiple times (overridden).

**Comment by GWRon** [comment]
Created an reproduceable sample ... closing this issue and creating a new one for bcc-ng
