### ISSUE TITLE
Error trying to access individual chars/bytes in undocumented string type

### ISSUE THREAD

**Issue by thareh** [bmx-ng/brl.mod#169]
Hi,
I came across code that uses $z as a type for a variable.

**Firstly**: I couldn't find any information about what $z does, could someone enlighten me?

**Secondly**: Trying to access individual characters or bytes by treating it as an array produces an error:
> error: request for member 'buf' in something not a structure or union
>    brl_standardio_Print(bbStringFromInt((bbt_test)->buf[0U]));
>                                                   ^~

So maybe that type of string should be limited somehow and a more user friendly error message presented or something?

**Example**:
> Local test$z = "test"
> 
> Print test[0]

Also, is there someone whom I can ask these types of questions? I'd like to learn more advanced stuff and hopefully contribute in the future, but sadly the documentation is lacking in the more advanced areas and I don't want to clutter the repository with my nonsense.

Thanks!

**Comment by woollybah** [comment]
Tut. Digging deep in code is never going to end well !

`$z` is a legacy lazy "String-to-C-string" conversion. It is generally only used when communicating with a 3rd-party library/function that requires a C string.

It basically does something like this
```blitzmax
Extern
   Function some_external_func(txt$z)
End Extern

some_external_func("Hello World")
```
... which translates to ...
```blitzmax
Local tmp:Byte Ptr = "Hello World".ToCString()
some_extern_func(tmp)
MemFree(tmp)
```
... except it's translated to C.

There's also `$w` which is the "Short Ptr" version.

I personally tend not to use it. I'll usually pass a String (`BBString*`) to a glue function, and do the conversion in there.

You can ask questions here : https://discord.gg/5D9KJw

**Comment by thareh** [comment]
Yeah alright, thank you for the explanation Brucey! :)
