### ISSUE TITLE
brl.blitz

### ISSUE THREAD

**Issue by nikikust** [bmx-ng/brl.mod#170]
After i updated brl.mod this error appeared:
![brl blitz](https://user-images.githubusercontent.com/52621231/71547947-d0f9b080-29b7-11ea-96c6-cc3861232569.PNG)
in "builtin.bmx".
Maybe I need to update another libs? Thank you

**Comment by GWRon** [comment]
Before updating brl.mod you need to update your bcc (fetch, compile, replace).

**Comment by nikikust** [comment]
i need this?
https://github.com/bmx-ng/bcc

**Comment by GWRon** [comment]
Yes. Compile its bcc.bmx with the old brl.mod

Then replace the existing bcc with the new one...and finally you can update brl.mod

**Comment by nikikust** [comment]
where can i get prelast ( :) ) version of brl?

**Comment by GWRon** [comment]
Click on the commits link on github... Right of the commit you want...there is this "< >" link...click on it and then download as usual.

**Comment by nikikust** [comment]
Yes! I did this :). Thank you! I found old archive with bmng earlier then commit which i need. bcc was compiled correctly.
