### ISSUE TITLE
IsNan error: "Unable to convert from Void to Int."

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/brl.mod#177]
I just tried the IsNan example code (below) from the docs in NG but get the above error.

Does work in Vanilla [tm].

**Not important for me, just reporting!**

```
SuperStrict

For Local f:Float=-0.4 Until 0.4 Step 0.2
    If IsNan(Sqr(f)) = True Then
       Print "Square Root of "+f+" is not a real number"
    Else
       Print "Square Root of  "+f+" = "+Sqr(f)
    EndIf
Next

```

**Comment by HurryStarfish** [comment]
Oh yeah, [the return type for `IsNan` is missing](https://github.com/bmx-ng/brl.mod/blob/ad062a7499c4784cd2cc1ac46830ae4121cd5c66/math.mod/math.bmx#L33). Same goes for `IsInf`.

As a side note:
It is not recommended to do `= True` comparisons. BlitzMax unfortunately doesn't have a boolean type, so `Int` gets used instead. Any number other than 0 is considered to be "truthy", but in `If x = True Then`, the Then-block will only execute when `x` is 1, which can lead to confusion/bugs. `If x Then` should be used instead. If this is in the docs, it should probably be changed.

**Comment by DruggedBunny** [comment]
Nice work, would never have spotted that simple thing!

Never run into the If x = True/1 thing, very interesting.

Many thanks.
