### ISSUE TITLE
many modules failing on stream.bmx, on raspberry pi

### ISSUE THREAD

**Issue by Jeromelab** [bmx-ng/brl.mod#18]
It returns always the same error:

Compiling:stream.bmx
Compile Error: Expression has no scope
[/Desktop/BlitzMax/mod/brl.mod/stream.mod/stream.bmx;386;0]

**Comment by Jeromelab** [comment]
List of modules not compiling(scope errors on stream.bmx, socket.bmx) on raspberry pi/raspbian with
bmk 2.20 linux-arm / gcc 040603 (cpu x4)

 appstub
audio
audiosample
bank
bankstream
basic
bmploader
endianstream
eventqueue
filesystem
freeaudioaudio
freetypefont
glmax2d
gnet
graphics
httpstream
jpgloader
linkedlist
max2d
maxlua
maxutil
oggloader
openalaudio
pixmap
pngloader
polledinput
ramstream
reflection
retro
socket
socketstream
standardio
stream
system
systemdefault
textstream
tgaloader
timer
wavloader

**Comment by woollybah** [comment]
Everything appears to be working with the latest bcc and bmk. You can download a pre-built set here : https://github.com/bmx-ng/bmx-ng/releases
