### ISSUE TITLE
Possible quaternion.EulerXYZ error? (Angles doubled.)

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/brl.mod#180]
Hi Brucey,

Disclaimer: I don't know what I'm doing and am winging it.

I ran into a problem with my crude 3D engine whereby I seem to have to pass in half the number of degrees I want for rotation on a given axis -- it rotates double the degrees specified, so a yaw of 45 shows a cube rotated by 90 degrees.

I think it might be an error during encoding to quaternions, as the apparent error comes in after applying `my_quat.EulerXYZ (rotation_as_vector)`.

The engine's a bit complicated, over multiple files, but this code seems to show the same problem. Some explanatory points will follow!

```
' Using YAW only...

Local angle:Float = 45

Local pitch:Float = 0
Local yaw:Float = angle
Local roll:Float = 0

' Init quat...

Local rotation_quat:SQuatF = New SQuatF (0.0, 0.0, 0.0, 0.0).EulerXYZ (New SVec3F (0.0, 0.0, 0.0))

' Yaw as matrix...

Local yaw_mat:SMat4F = SMat4F.Rotation (New SVec3F (0, 1, 0), angle)

Print ""
Print "Matrix for yaw of angle " + angle + " degrees:"
Print ""
Print ATan2 (yaw_mat.g, yaw_mat.k) ' Pitch
Print ASin (yaw_mat.i) ' Yaw
Print ATan2 (yaw_mat.e, yaw_mat.f) ' Roll

Print ""
Print "Encoding angles to quat..."

' Yaw vector...

Local yaw_vec:SVec3F		= New SVec3F (pitch, yaw, roll)

' Update quat with yaw vector...

rotation_quat	= rotation_quat.EulerXYZ (yaw_vec)

' Get matrix from quat...

Local test:SMat4F	= SQuatF.ToMat4 (rotation_quat)

'PrintMat (test)

Print ""

Print "Looking for " + angle + " (or rotational equivalent)..."
Print ""
Print ATan2 (test.g, test.k) ' Pitch
Print ASin (test.i) ' Yaw
Print ATan2 (test.e, test.f) ' Roll

```

I _think_ my euler-angles-from-matrix code there is working, or at least it seems to return valid angles for one axis at a time...

```
Local yaw_mat:SMat4F = SMat4F.Rotation (New SVec3F (0, 1, 0), angle)

Print ATan2 (yaw_mat.g, yaw_mat.k) ' Pitch
Print ASin (yaw_mat.i) ' Yaw
Print ATan2 (yaw_mat.e, yaw_mat.f) ' Roll
```

(I gather I may need to take some edge cases into account.)

Note that I then encode the angles instead to a quaternion, then extract the matrix, and that's where it appears to double the value.

Would it be possible to get some 'official' `quat.ToEulerXYZ ()` [and XZY, etc] functions, or would it be bloating things too much? I realise my code may be suspect but it seems to work on the unmodified matrix at least!

Apologies in advance if I'm just using it all wrongly... :/

**Comment by woollybah** [comment]
Don't imagine for a moment that I have any idea what I'm doing either. 🤓

**Comment by DruggedBunny** [comment]
Doh! I like the fix, ha ha. Thanks Brucey!

**Comment by DruggedBunny** [comment]
Oh, you even did the feature request! Awesome as ever, thanks again.
