### ISSUE TITLE
Sorry... ToEulerXYZ!

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/brl.mod#181]
Thanks for ToEulerXYZ, Brucey. The quat fix seems to be fine now, but I think ToEulerXYZ isn't quite right.

**Note: no rush for me, I can happily get on with my quat rotation stuff now at least!**

The yaw in this sample is going from **0 to 90 to 0**, then **0 to -90 to 0**, never passing - or + 90 degrees, so 89 degrees and 91 degrees as shown here both read as 89 degrees:

![science](https://user-images.githubusercontent.com/1781537/86181784-93bcd980-bb26-11ea-89ca-44d7605f8eea.png)

I would expect it to pass through 0... 89, 90, 91 ... 180, and flip negative going the other way (0... -89, -90, -91 ... -180). Or arguably 0-360, though I think Blitz3D used -/+ 180.

```
Local pitch:Float	= 0
Local yaw:Float		= 0
Local roll:Float	= 0

' Init...

Local rotation_vec:SVec3F		= New SVec3F (pitch, yaw, roll)
Local rotation_quat:SQuatF		= New SQuatF (0.0, 0.0, 0.0, 0.0).EulerXYZ (rotation_vec)

' Go...

For yaw = -5 To 365

	rotation_vec	= New SVec3F (pitch, yaw, roll)
	rotation_quat	= rotation_quat.EulerXYZ (rotation_vec)
	
	Print "Pitch:~t"	+ rotation_quat.ToEulerXYZ ().x
	Print "Yaw:~t"		+ rotation_quat.ToEulerXYZ ().y
	Print "Roll:~t"		+ rotation_quat.ToEulerXYZ ().z
	Print ""
	
Next

```

This is the output as it goes through 90 degrees -- note that **Pitch and Roll flip to 180 also**:

```
Pitch:	0.000000000
Yaw:	88.0000229
Roll:	0.000000000

Pitch:	0.000000000
Yaw:	89.0000458
Roll:	0.000000000

Pitch:	0.000000000
Yaw:	89.9802170			' 90 degrees here
Roll:	0.000000000

Pitch:	180.000000			' Pitch and Roll have flipped to 180, exact opposite of 0
Yaw:	89.0000458
Roll:	180.000000

Pitch:	180.000000
Yaw:	88.0000229			' Yaw is going back down instead of negative or up towards 180
Roll:	180.000000

Pitch:	180.000000
Yaw:	87.0000381
Roll:	180.000000

```

Oh, just to pile on the work -- **I don't need this**, but you have EulerXYZ, EulerZXY, EulerZYX, etc, so probably ought to have the equivalent ToEulers (?).

Thanks as always!

**Comment by woollybah** [comment]
Should be fixed now.
I've added a `ERotationOrder` enum, and refactored the XYZ methods to take the enum as an arg.
`EulerXYZ` becomes `EulerRotate` - the default is to use XYZ rotation.
The `ToEuler` method also takes the enum as an arg.

**Comment by DruggedBunny** [comment]
Hi Brucey, I think something's not quite right still -- in fact, it seems to be doing exactly the same thing! Pitch and Roll both flip to -180.0 as the Yaw passes through 90 degrees, and yaw never passes plus or minus 90.

Here it is updated and narrowed down to the 88 to 92 degree range. Notice that as the angle turns to 91, yaw goes back down to 89 and pitch/roll both flip to -180:

```
Local pitch:Float	= 0
Local yaw:Float		= 0
Local roll:Float	= 0

' Init...

Local rotation_vec:SVec3F		= New SVec3F (pitch, yaw, roll)
Local rotation_quat:SQuatF		= New SQuatF (0.0, 0.0, 0.0, 0.0).EulerRotate (rotation_vec)

' Go...

Print ""

For yaw = 88 To 92

	Print "Angle: " + Int (yaw)
	Print ""
	
	rotation_vec	= New SVec3F (pitch, yaw, roll)
	rotation_quat	= rotation_quat.EulerRotate (rotation_vec)
	
	Print "Pitch:~t"	+ rotation_quat.ToEuler ().x
	Print "Yaw:~t"		+ rotation_quat.ToEuler ().y
	Print "Roll:~t"		+ rotation_quat.ToEuler ().z
	Print ""
	
Next

```

I get output of:

```
Angle: 88

Pitch:	-0.000000000
Yaw:	88.0000229
Roll:	-0.000000000

Angle: 89

Pitch:	-0.000000000
Yaw:	89.0000458
Roll:	-0.000000000

Angle: 90

Pitch:	0.000000000
Yaw:	89.9802170
Roll:	0.000000000

Angle: 91

Pitch:	-180.000000
Yaw:	89.0000458
Roll:	-180.000000

Angle: 92

Pitch:	-180.000000
Yaw:	88.0000229
Roll:	-180.000000

```

Similar results as you go around the compass, with pitch and roll sometimes positive 180.

**Comment by woollybah** [comment]
I've added some more stuff, to fill it out a bit.

Have a look here : https://www.andre-gaschler.com/rotationconverter/

I can replicate what you are seeing by entering 0, 91, 0 on the left, using XYZ for left and right.
If I change to XZY on the right, I get the result you are expecting.

SQuatF works like this too.

**Comment by DruggedBunny** [comment]
OK, I see that now, yes -- so it probably is right, then!

I guess x and z flipping to -180 has the effect of changing what the 89-90-89 y value 'means'... I can't picture it properly, but that must be it.

I like the CreateFroms too!

I did manage to get my little engine's rotations working from Quats only (ditching Mats) yesterday, but there's still much for me to figure out yet.

Thanks for putting so much into this, will shut up and get on with trying to use it!
