### ISSUE TITLE
How to check brl.io for errors

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#188]
assume you have a secretfile.zip with an "invalid" (non understood) password encryption (like in the attachment)

Now I want to understand why "LoadText()" fails. 
```
SuperStrict

Framework Brl.StandardIO
Import Brl.FileSystem
Import Brl.io

MaxIO.Init()

MaxIO.Mount("secretfile.zip", "dir_original")
Try
    print LoadText("dir_original/secretfile.txt$blitzmax")
Catch ex:Object
    Print ex.ToString()
    Throw bmx_PHYSHS_getLastError()
End Try

End
```

how to avoid the segfault when trying to throw the last error? How to properly read the pub.mod/physfs.mod errors / brl.io errors?

[secretfile.zip](https://github.com/bmx-ng/brl.mod/files/5052942/secretfile.zip)

**Comment by woollybah** [comment]
You could use the following to determine whether there was an IO specific error : 
```
	Local code:EMaxIOErrorCode = MaxIO.GetLastErrorCode()
	If code <> EMaxIOErrorCode.OK Then
		Throw MaxIO.GetErrorForCode(code)
	End If
```

Simply calling `Throw MaxIO.GetLastError()`, may result in no error message if there was no last error.

**Comment by GWRon** [comment]
Thanks
