### ISSUE TITLE
brl.appstub fail to compile 

### ISSUE THREAD

**Issue by olejr** [bmx-ng/brl.mod#19]
Windows 8.1 x64, MinGW (x64) v4.8.1, bmk v3.00 (compiled as x86)

bmk makemods -g x64 

Error out with:
Interal Error:
[/mod.brl.mod/appstub.mod/debugger_mt.stdio.bmx;86;0]

Same thing when trying only to compile brl.appstub

**Comment by GWRon** [comment]
You could find out what causes this error:
- bmk makemods -v -g x64
-> should show what it did when erroring out

- open up MaxIDE and build bcc in debug mode with "command line params" (available via menu) according to the command used by bmk
-> should give you "debug"-opportunities with bcc (and you see why and where it errors out)

Maybe this helps Brucey to find things faster.

**Comment by woollybah** [comment]
It seems perhaps that ```:Shr``` doesn't support ```Long```.

**Comment by woollybah** [comment]
```Internal Error```'s are a bit rubbish as a useful indicator to finding out what went wrong.

**Comment by olejr** [comment]
As it fail on line 86 
```
		val:Shr 4

```
Your comment about :Shr not supporting "something" seem right.
Should mention that this isn't a bmk v3 bug, had it before that too..

Also tried 'bmk makemods -v -g x64', but didn't really get more useful info.
