### ISSUE TITLE
[FileSystem.mod] add option to "lock" to OpenFile etc. ?

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#192]
For now you can have multiple file handles to the same "WriteFile", "OpenFile" etc.

Each handle has its own file position and so on. This is fine.

But what if you want to have exclusive write/read to a file? the OSes provide different abilities to it:
https://en.wikipedia.org/wiki/File_locking

Maybe add a simple options flag to the functions so we could do a
ReadFile(..., FILE_EXCLUSIVE_READ)
which calls flock() and makes follow up tries to read this file (or write...) fail until file handle is closed (or "lock" is removed).

So ... maybe it should even have some kind of `LockFile(filehandle)` and `UnlockFile(filehandle)` added?

**Comment by woollybah** [comment]
Seems like it only properly works on Windows...  and given the portability issues likely to be encountered, it sounds like it would be a big problem to get right - if it works at all.

**Comment by GWRon** [comment]
Ok. Kind of a pity (...the downside of crossplatform and "lowest common denominator")

Couldn't this be done with conditional switches and some thrown errors if not supported? Hmm...nah also not the best thing.
