### ISSUE TITLE
[color.mod] Request: operator overloads

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#194]
Hi,

I just want to request the addition of "operator overloads" (and maybe "comparison") for the `SColor8` struct.

What I am looking for is something like this:
```BlitzMax
local colWhite:SColor8 = SColor8.white
local colBlack:SColor8 = SColor8.black
local colCustom:SColor8 = new SColor8(255,255,255,255) 'also white...

'equals?
If colWhite = colCustom Then print "custom color is white"

'add colors
local colCustom2:SColor8 = colWhite + colBlack '128,128,128,255
'subtract is a bit tricky -- read "incorrect" (see alpha...)
local colCustom3:SColor8 = colWhite - colBlack '255,255,255,255
```

So while addition/subtraction/multiplication etc might not be ... suited for all cases (as you might better do "multiplication" when mixing colors, and "addition" when overlaying), I think the "equals" can be quite handy.

**Comment by woollybah** [comment]
Why 128 and not 127?

**Comment by GWRon** [comment]
Hmm... 127+127 = 254
128+128 in bytes... = 255

...maybe this why? On the other side "ceiling" will lead. To issues when doing 1+0 div 2... It never becomes 0 then.

**Comment by GWRon** [comment]
Also...maybe only comparison of = and <> is useful.

Is white > black? What is green minus red?

Orange minus yellow is red...or not?

**Comment by woollybah** [comment]
I don't think anything other than equality test operators will be generally helpful.
