### ISSUE TITLE
String.FromUTF8String - TStream with 2048byte files appends random characters

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#196]
Discord-user Thareh informed via the issues-channel that files with 2048 bytes length create random characters when opened in MaxIDE ....
The same also happens when doing "Loadtext(file)" - so this is not an MaxIDE issue.

![](https://imgur.com/uO1u1pt.png)

Sometimes the content differs (might depend on what comes "next" in the memory) but if you do not do something "different" on your computer, then ist will be some MaxIDE-stuff which gets appended.

Testfiles:
[2048.zip](https://github.com/bmx-ng/brl.mod/files/5402935/2048.zip)

**Comment by GWRon** [comment]
I cannot confirm the stuff for "Loadtext" (there it does not output any random stuff to ME). also TFilestream.ReadFile() seems to do what it should (when reaching 2048 chars)

**Comment by thareh** [comment]
Here's the smallest example of the issue that I can produce:
```
Framework BRL.StandardIO

Repeat
	
	Print LoadText("1024.bmx")
	
	Delay 5
	
Forever
```

1024.bmx is a file that's exactly 1024 bytes big filled with whatever but in my case it's filled with lowercase a's.

After some iterations random characters starts appearing at the end of the a's.

(Windows)

**Comment by GWRon** [comment]
As said - I cannot confirm this for "LoadText" - but you can do.
So maybe dive through the code and add some debug prints to TFilestream.Readfile() ?

At least there the initial buffersize is 1024 ... which corresponds to your text length - maybe something leads to a different sized array? the array is ":short" but "integers" are written (what happens if the ints are negative - somehow) or such stuff ?

**Comment by GWRon** [comment]
Oh ... LoadText uses a different approach than TFileStream.Readfile() ... this code there looks more likely to be able to "break"  - maybe it copies more than it should (you could check if size exceeds your "size").

**Comment by GWRon** [comment]
the files are loaded via this piece of code:
```
		If checkForUTF8 And IsProbablyUTF8(data, size) Then
			Return String.FromUTF8String(data)
		Else
			Return String.FromBytes( data,size )
		End If
```

Seems the issue is related to `bbStringFromUTF8Bytes` - as MaxIDE does not append odd characters when telling the "LoadText()" there to not "checkForUTF8".

**Comment by GWRon** [comment]
Closing this issue - raising new one (with reproduceable sample).
