### ISSUE TITLE
[Mac OS] Brl.Blitz - Mutex performance and UnlockMutex() returns albeit not unlocked (yet)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#229]
Heya,

I have this code here:
```Blitzmax
print "base.gfx.gui.scroller.bmx: REGISTERING EVENTS ==============="
        AddEventListener(EventManager.registerListenerFunction( GUIEventKeys.GUISlider_SetValueByMouse, onScrollHandleChange, scrollHandle ))
        'listen to changes via scroller buttons
        AddEventListener(EventManager.registerListenerFunction( GUIEventKeys.GUIObject_OnScrollPositionChanged, onScrollPositionChanged, self))
print "base.gfx.gui.scroller.bmx: REGISTERING EVENTS DONE ==============="
```
which at the end calls this:
```Blitzmax
    Method RegisterListener:TEventListenerBase(eventKey:TEventKey, eventListener:TEventListenerBase)
        If not TryLockMutex(_listenersMutex)
            TLogger.Log("RegisterListener()", "Mutex was still locked, waiting. value=" + _lastListenerMutexValue, LOG_DEBUG)
            LockMutex(_listenersMutex)
            _lastListenerMutexValue = "RegisterListener() " + eventKey.text.ToString()
        EndIf
        Local listeners:TObjectList = TObjectList(_listeners.ValueForKey(eventKey.id))
        If Not listeners
            listeners = New TObjectList
            _listeners.Insert(eventKey.id, listeners)
        EndIf

        listeners.AddLast(eventListener)
        UnlockMutex(_listenersMutex)

        Return eventListener
    End Method
```

So each `AddEventListener()` will
- tryLockMutex()
- if this fails print a log message and then finally wait for the mutex until available
- once available it stores the information who called it as last
- unlockMutex()

On my mac mini (ancient!) I see this then:
```
base.gfx.gui.scroller.bmx: REGISTERING EVENTS ===============
[11:36:41] DBG      |                : Mutex was still locked, waiting. value=RegisterListener() GUIObject.OnMouseDown
[11:36:41] DBG      |                : Mutex was still locked, waiting. value=RegisterListener() GUISlider.SetValueByMouse
base.gfx.gui.scroller.bmx: REGISTERING EVENTS DONE ===============
```
There is no other thread using this mutex. Yet this serially executed 2 method calls result in the second call waiting for the mutex of the first call being unlocked.

This means while the first method calls "UnlockMutex()" this wont happen very then ... but the final "unlocking" takes place a bit later.

While looking for it I found some articles/questions about the performance of Mutexes on OS X.
https://stackoverflow.com/questions/33991644/why-is-performance-of-pthread-mutex-so-bad-on-mac-os-x-compared-to-linux/52649426#52649426
which links to 
https://blog.mozilla.org/nfroyd/2017/03/29/on-mutex-performance-part-1/

which talks about a mac os specific mutex command one could utilize to change from the "fair use" approach to "first hit" (as it is on Linux).

The performance test there is quite... interesting (as that benchmark there became a magnitude faster).
Nonetheless I am not sure why I see the output above (that a "non threaded" sequence leads to waiting for the mutex).

Maybe one could create an optional `UnlockMutex(mutex:TMutex, waitForUnlockFinish:Int = False)` so one could define to have the thread wait for the mutex to be "really" unlocked.

**Comment by woollybah** [comment]
Here's the performance test...
```
SuperStrict

Framework BRL.standardio
Import BRL.Threads


Local numThreads:Int = 10

Local state:TGlobalState = New TGlobalState

Local threadStates:TPerThreadState[] = New TPerThreadState[numThreads]

state.lock.Lock()

For Local i:Int = 0 Until numThreads
	threadStates[i] = New TPerThreadState(state, i)
	threadStates[i].threadHandle = TThread.Create(ThreadFunc, threadStates[i])
Next

Delay 1

state.lock.Unlock()

Local millisecondsPerTest:Int = 100

Delay millisecondsPerTest

state.lock.Lock()
state.keepGoing = False

For Local i:Int = 0 until numThreads
	Print threadStates[i].aquisitions
Next

state.lock.Unlock()

For Local i:Int = 0 Until numThreads
	threadStates[i].threadHandle.Wait()
Next

Type TPerThreadState
	Field globalState:TGlobalState
	Field threadHandle:TThread
	Field threadIndex:Int
	Field aquisitions:Int

	Method New(globalState:TGlobalState, threadIndex:Int)
		Self.globalState = globalState
		Self.threadIndex = threadIndex
		Self.aquisitions = 0
	End Method
End Type

Type TGlobalState
	Field lock:TMutex
	Field keepGoing:Int

	Method New()
		keepGoing = True
		lock = TMutex.Create()
	End Method
End Type

Function ThreadFunc:Object(data:Object)
	Local state:TPerThreadState = TPerThreadState(data)
	Local globalState:TGlobalState = state.globalState

	While globalState.keepGoing
		globalState.lock.Lock()
		state.aquisitions :+ 1
		globalState.lock.Unlock()
	Wend
End Function
```
I think I got the micro->millis conversion right.

Here's an example set of results on my machine
```
502877
462015
432564
424050
519550
608308
379875
361239
359793
426134
```
It appears my version of macOS is not playing fair, and requires no changes?

**Comment by woollybah** [comment]
I've committed a change which will attempt to use first fit on macOS, but it's only properly support from 10.14, as far as I can tell. May even be the default on current versions.

**Comment by woollybah** [comment]
Interestingly, if I set it to fair, I get the following results :
```
7795
7795
7794
7795
7794
7794
7794
7794
7794
7794
```

**Comment by GWRon** [comment]
Think this is what others wrote too..that times are way better then.

But might have side effects (as linked)

**Comment by woollybah** [comment]
Given it's now the default option on macOS, it's somewhat unlikely there are terrible side effects.

**Comment by GWRon** [comment]
I referred to what the mozilla devs mentioned in the bug reports the mozilla dev blog linked .

Dunno if that was relevant but thought I better remind about it ;-)
