### ISSUE TITLE
Segfault 32-bit strings

### ISSUE THREAD

**Issue by thareh** [bmx-ng/brl.mod#230]
Hey,

Running the code from the following archive: https://public.thareh.se/blitzmax/Segfault.7z produces a segfault, usually when the counter hits 30 or so.

Seems related to strings and UTF8 from what I can tell using GDB, and it's only 32-bit I think as well.

Thanks,
-- Thareh

**Comment by GWRon** [comment]
The download is no longer available - if the code still segfaults you might consider adding it to here as attachment.

**Comment by thareh** [comment]
I'm afraid I don't have the file anymore so I'll just close this.
