### ISSUE TITLE
[Brl.random] used by brl.retro and brl.basic

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#233]
```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import brl.basic
'or brl.retro - as this imports brl.basic
'Import brl.retro 

Import Random.Xoshiro

Print Rnd(100)
```

throws this message:
```
Random already installed : RandomDefault
```

So how to use "xoshiro" without having to check what modules a "brl.basic" imports (eg you want to use `Mid()` of brl.retro + `random.xoshiro`).

Thought one could do it similar to "drivers": `SetRandomGenerator("xoshiro")` and `GetRandomGenerator:TRandom()` or similar. Maybe adding such stuff would be useful.
At least the ability to "replace" an already added random generator would be ... crucial. In other words:
```BlitzMax
Import brl.random
Import random.xoshiro
```
would set "xoshiro" as the one to use (as it was called the last - and contains a new trandom-creation at the end of the file).

**Comment by woollybah** [comment]
Should be fixed now.
