### ISSUE TITLE
[io.mod] Missing API functions and "absolute paths"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#235]
Using `brl.io` is a bit ... barebone for now.
you can set the write dir, but not retrieve it (`GetWriteDir()` missing). 

I copy to here an example of discord user "mingw" (which I extended a bit):
```BlitzMax
SuperStrict
Framework Brl.StandardIO

Import brl.io


MaxIO.Init()
Local prefDir:String = MaxIO.GetPrefDir( "redstorm",AppTitle )

print "basedir: " + MaxIO.GetBaseDir()
print "prefdir: " + prefDir

MaxIO.SetWriteDir( prefDir ) 
print "LastError: " + MaxIO.GetLastError()
'Local stream:TStream=WriteStream( prefDir +"/" + "settings.ini" )
Local stream:TStream=WriteStream( "settings.ini" )
print "LastError: " + MaxIO.GetLastError()

If stream
    WriteStdout( "OK!" )
Else
    WriteStdout( "OOOPS!" )
End If
```

As you see you need to use "/" as MaxIO does not expose the "directory separator" to use.
Also you can only save this file when using the "relative" URI (`"settings.ini"`). The absolute URI results in "not stream".

So output with local uri:
```
basedir: /home/ronny/Arbeit/Projekte/Testcodes/bmx tests/
prefdir: /home/ronny/.local/share/BlitzMax Application/
LastError:
LastError: not found
OK!
```

with absolute uri:
```
basedir: /home/ronny/Arbeit/Projekte/Testcodes/bmx tests/
prefdir: /home/ronny/.local/share/BlitzMax Application/
LastError:
LastError: not found
OOOPS!
```

Dunno what is the best practice here ... despite just writing "locally" into a specific write directory.
Aside of that it would be good to see some more of the basic PHYSFS-functionality being exposed.

I simply thought passing an absolute path to `WriteStream()` kinda avoids maxio and handles it on its own but seems once maxio is initialized you need to do it their way (which is OK).

Also I would like to know how things like `maxio.OpenWrite()` are used (it is in brl.mod - so I assume it is for "convenient enduser-use")

**Comment by GWRon** [comment]
Will close the issue.
- additional getters were recently added
- to allow "writestream" you need to set a write dir before: `MaxIO.SetWriteDir(prefDir)`

I personally would have preferred that there is a "default write dir" - which is the application folder. That way you can introduce "MaxIO" without having to adjust much of your existing code base.

**Comment by woollybah** [comment]
When is the application folder ever a viable default location in which to write data?
Typically an application would write into some OS standard application data folder, which I assume is what `GetPrefDir()` is meant to provide.

**Comment by GWRon** [comment]
Portable applications tend to save stuff where they reside.

Else it might be good to have some kind of default (or easy way to set it up) so you can easily move to brl.io.

**Comment by GWRon** [comment]
For our game I would simply take care of de-/initializing maxIO on our own.

Yet maxio is not shipped with the last official build (hint hint for more current releases ;-))
