### ISSUE TITLE
[random.mod] Rand() leading to issues if "maxValue - minValue > signed-int-maximum" 

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#246]
as @thareh did mention on Discord:
```
Hey peeps,
Using Rand(-2147483648, 2147483647) seems to not work very well, am I missing something or is there a bug?
```

I looked at the random.mod/random.bmx file and found this:
```Blitzmax
	Method Rand:Int(minValue:Int, maxValue:Int = 1)
		Local Range:Int=maxValue-minValue
		If Range>0 Return Int( RndDouble()*(1+Range) )+minValue
		Return Int( RndDouble()*(1-Range) )+maxValue
	End Method
```

We have multiple issues here:
"range" is kinda limited to "half an integer" (as it can only be positive .. but a signed integer has both).
In the other lines we have a similar thing: the first part of the sum (`rnddouble()*(1 +- range)`) can be bigger than the integer limit ... yet we cast it BEFORE adding the minValue (which will bring it down below the integer limit).

Means:
- "range" must be unsigned int - or long.
- integer cast must be done after summing up

So this works:
```Blitzmax
	Method Rand:Int(minValue:Int, maxValue:Int = 1)
		Local Range:Long = Long(maxValue) - Long(minValue)
		If Range>0 Return Int( RndDouble()*(1+Range) + minValue )
		Return Int( RndDouble()*(1-Range) + maxValue )
	End Method
```

~~and this should do too (am not sure if the range-line works with `= UInt(int - int)` - but it looks like it does).~~
<strike>
```Blitzmax
	Method Rand:Int(minValue:Int, maxValue:Int = 1)
		Local Range:UInt = UInt(maxValue - minValue)
		If Range>0 Return Int( RndDouble()*(1+Range) + minValue )
		Return Int( RndDouble()*(1-Range) + maxValue )
	End Method
```
</strike>

**Comment by thareh** [comment]
Hey Ron,

Thank you for looking into the issue. Your solution using a Long seems to work well, the UInt one not so much I'm afraid.

Solving it using UInt would be ideal cause then it can be translated to work for Random.SFMT's Rand64 function as well using ULong.

I'll look into it later and try to solve it if you don't feel obliged 😄 

Thanks!
-- Thareh

**Comment by GWRon** [comment]
Yeah .. `uint` cannot work ... how could I even think it would.
I guess it calculates "int - int" first and then casts ... which is correct - but does not get rid of the "limitation" as it calculates in the limits of "signed integer".

So we would need to ensure that at least one of the numbers is "big enough" to make BCC use the "bigger primitive" (here `long`). Means this should do too (casting only one to `long`:
```
Local Range:Long = Long(maxValue) - minValue
```

Will edit my above post accordingly
