### ISSUE TITLE
[brl.io] ReadDir() requires mount appDir as appDir, Load(localFileURI) not working

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#248]
```Blitzmax
SuperStrict
Framework Brl.StandardIO
Import Brl.IO
Import Brl.Filesystem


MaxIO.Init() 'enable virtual file system handling
Local myAppDir:String = MaxIO.GetBaseDir()
print "app directory: " + myAppDir

'THIS mount is required to make it work
'MaxIO.Mount(myAppDir, myAppDir)


PrintFiles(AppDir)

function PrintFiles(dir:String)
	Local dirHandle:Byte Ptr = ReadDir(dir)
	Repeat
		Local fileName:String = NextFile(dirHandle)
		If fileName = "" Then Exit
		print fileName
	Forever
End Function
print "last error:" +  MaxIO.GetLastError()
```

So if you just initialize MaxIO you won't be able to write, load ... a file from the application folder.

More of an issue is that `ReadFile()` and others are no longer working with relative-to-application-URIs.
First you define `SetWriteDir()` - saving a file to there works with "local URIs" but loading doesn't:

```BlitzMax
SuperStrict
Framework Brl.StandardIO
Import Brl.IO
Import Brl.Filesystem


MaxIO.Init() 'enable virtual file system handling

Local myAppDir:String = MaxIO.GetBaseDir()
MaxIO.Mount(myAppDir, myAppDir, True)
'required to be able to write to application directory
MaxIO.SetWriteDir(myAppDir)
print "app directory: " + myAppDir

Local file:TStream = WriteFile("test.txt")
If Not file Then RuntimeError "failed to open test.txt file for writing" 
file.Writeline("test")
file.Close()

'THIS would work
'file:TStream = ReadFile(myAppDir + "/test.txt")
'THIS doesn't
file:TStream = ReadFile("test.txt")
If Not file RuntimeError "failed to open test.txt file for reading"
While Not Eof(file)
    Print ReadLine(file)
Wend
file.Close()
```

**Comment by woollybah** [comment]
By enabling MaxIO you are essentially sandboxing the application from the filesystem.

You then need to give read access to a folder or archive contents by mounting it.
So, if you want open up read access to the application dir, you can do something like :
```
MaxIO.Mount(MaxIO.GetBaseDir())
```
By not providing a mount point, you are basically saying, mount at `/`. Files at this level do not require a path prefix.

If you want to write to the filesystem, you need to explicitly set a write dir.

**Comment by woollybah** [comment]
Some examples..
```
' option 1
MaxIO.Mount(myAppDir)
PrintFiles("/") ' empty String is equivalent

' option 2
MaxIO.Mount(myAppDir, myAppDir)
PrintFiles(myAppDir)

' option 3
Local dir:String = Realpath(AppDir)
MaxIO.Mount(dir)
PrintFiles("/")
```

**Comment by GWRon** [comment]
Yeah, I already tried that now (after your first reply) - stupid me thought I need to mount it in an "absolute path" way.

Now ... it is kinda logical to mount whatever (here "myAppDir") to "root" (in the sense of "root directory of the app").
