### ISSUE TITLE
Wrong number of arguments to SendMessage

### ISSUE THREAD

**Issue by Leushenko** [bmx-ng/brl.mod#26]
SendMessage is declared with only two arguments in `blitz_object.h`, yet code is (correctly) generated to pass it three, resulting in the C compiler getting upset:

    error: too many arguments to function call, expected 2, have 3
            BBOBJECT volatile bbt_=(bbt_win)->clas->SendMessage(bbt_win,&_s5,o->__m_eventlog_eventlog_msgs );
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by woollybah** [comment]
SendMessage is declared with only two arguments in standard BlitzMax too.
One must assume this is a general issue that somehow the generated asm avoids...
