### ISSUE TITLE
Modules, Windows and latest bcc (overloading)

### ISSUE THREAD

**Issue by olejr** [bmx-ng/brl.mod#27]
On Windows these fail to build because wrong argument type(s).

brl.mod/dxgraphics.mod/d3d9graphics.bmx
brl.mod/directsoundaudio.mod/directsoundaudio.bmx

**Comment by GWRon** [comment]
Surely just an issue to cast floats to int or so (int(floatParam)).

Maybe you could fork brl.mod and fix this on your own (to save Brucey some time) ?

**Comment by olejr** [comment]
Did fix it myself. Just put it here as a "reminder", but didn't make that clear as posting/typing on the phone is a pain.

**Comment by GWRon** [comment]
you might have seen Bruceys commit now...

**Comment by woollybah** [comment]
Fixed.
