### ISSUE TITLE
Receiving the following error building for Windows

### ISSUE THREAD

**Issue by braxtonrivers** [bmx-ng/brl.mod#48]
Apologies if this has already been mentioned elsewhere, building on Windows gives the following message with the latest commit

D:/BlitzMaxNG/BlitzMax/mod/brl.mod/dxgraphics.mod/.bmx/d3d9graphics.bmx.debug.win32.x64.c: In function '_bb_brl_dxgraphics_d3d9graphics':
D:/BlitzMaxNG/BlitzMax/mod/brl.mod/dxgraphics.mod/.bmx/d3d9graphics.bmx.debug.win32.x64.c:2429:39: error: incompatible types when assigning to type 'struct pub_directx_d3d9_D3DCAPS9' from type 'int'
   brl_dxgraphics_d3d9graphics__d3dCaps=pub_directx_d3d9_D3DCAPS9_New_ObjectNew();

**Comment by noroads2015** [comment]
I'm having the same problem.  Both 32 bit and 64 bit compile.  Using TDM64-GCC-5.1.0-2
