### ISSUE TITLE
Unable to convert from TSystemDriver to IWrappedSystemDriver.

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#59]
Fetched / compiled latest BMK
Fetched latest brl and pub.mod - and tried to run `/.bmk makemods -a -r brl` (brl to avoid the long pub.glew compilation times ;-))

```
Compile Error: Unable to convert from TSystemDriver to IWrappedSystemDriver.
[/BlitzMaxNG/mod/brl.mod/system.mod/driver.bmx;48;0]
Build Error: failed to compile (65280) /BlitzMaxNG/mod/brl.mod/system.mod/driver.bmx
```

Edit: hmm, will have to try to update bcc first :-)

**Comment by GWRon** [comment]
Ok, new bcc and it works. Closed.

**Comment by GWRon** [comment]
Ok ... another issue with that:

```BlitzMax
Import brl.map
Global mymap:tintmap=New tintmap
mymap.Insert(1,"hello")
```

```
Building untitled1
[ 97%] Processing:untitled1.bmx
[ 98%] Compiling:untitled1.bmx.console.release.linux.x64.c
[100%] Linking:untitled1
BlitzMaxNG/mod/brl.mod/systemdefault.mod/systemdefault.release.linux.x64.a(system.linux.bmx.release.linux.x64.o): In Funktion `_bb_brl_systemdefault_system_linux':
system.linux.bmx.release.linux.x64.c:(.text+0x370): Nicht definierter Verweis auf `brl_system_driver_Driver'
collect2: error: ld returned 1 exit status
Build Error: Failed to link /BlitzMaxNG/tmp/untitled1
Process complete

**Comment by GWRon** [comment]
Adding a "framework brl.standardio" makes it compile - because it does no longer use the system.mod (or so).

**Comment by woollybah** [comment]
I don't understand why you had to add brl.standardio?  It works here as expected...

**Comment by GWRon** [comment]
Without the framework command I got the above error. With framework command it workef

**Comment by woollybah** [comment]
Maybe your rebuild modules didn't work properly because systemdefault should have rebuilt and not have that error when trying to link.

**Comment by GWRon** [comment]
I rebuilt the modules via `./bmk makemods -r -g x64` and it compiled some stuff - also systemdefault.bmx. In the IDE I did not have "quick" enabled, just "quick scan"  and "overload warnings". Hmm, sometimes I think it misses "needed compilations". Maybe timestamps of files or so - especially when synchronizing via git.

**Comment by woollybah** [comment]
You should probably use -a to enforce rebuilds. -a with brl should rebuild all of the brl modules.

**Comment by GWRon** [comment]
For brl this is ok, but I avoid -a for pub.mod ... Pub.glew is not nice compilation time wise ;-)

**Comment by woollybah** [comment]
That shouldn't be such an issue after the latest commit...
