### ISSUE TITLE
makemods -a fails: Compile Error: Can't find interface for module 'brl.blitz'

### ISSUE THREAD

**Issue by Octav14n** [bmx-ng/brl.mod#6]
## Steps to reproduce:
1. Use Linux 64bit (Ubuntu 14.10 in my case)
2. clone bmx-ng/bcc.git and bmx-ng/bmk.git
3. clone bmx-ng/brl.mod.git and bmx-ng/pub.mod.git to "bmax/mod" (make sure the folder was empty before.)
4. build them via "BlitzMax/bin/bmk makeapp -t console -r -h bcc.bmx" (same for bmk.bmx)
5. copy to bmax/bin:
bcc
bcc.conf.default (remove ".default" and change the path in it)
bmk
core.bmk
make.bmk
6. execute "bmax/bin/bmk makemods -a"

### Note:
bmax is the directory for bmax-ng, "BlitzMax" is the directory of the legacy BlitzMax-Installation.

## expected result:
all mods (pub and brl) should be build without error messages.

## what actually happened:
compiler stops with the error: "Compile Error: Can't find interface for module 'brl.blitz'"
full ouptut: http://pastebin.com/9nUnykZj

**Comment by GWRon** [comment]
Is above still valid, if you do NOT use "bcc.conf" - or a one with correct path settings?

Else the issue should be closed for being "invalid" (now).

**Comment by Octav14n** [comment]
Wow, maybe there should be added a hint. Deleting "bcc.conf" did the trick. Thanks GWRon.
