### ISSUE TITLE
Timer/Event stuck

### ISSUE THREAD

**Issue by thareh** [bmx-ng/brl.mod#62]
I was playing around with maxgui and fmodaudio and noticed that maxgui acted really strange for some reason, repeating events. I traced it to fmodaudio and it has something to do with timers and events, check out the example file included (couldn't name it .bmx) - it should emit EVENT_FOO (1337) but it gets replaced with EVENT_BAR (1338) when emitting it after a WaitEvent() call.
[Bug.txt](https://github.com/bmx-ng/brl.mod/files/1821504/Bug.txt)

**Comment by GWRon** [comment]
Was the pool you (@woollybah ) just removed even doing something useful? Looked a bit like an unfinished/wip-thing forgotten in the module.

You added to the pool on emit, and ate it on create.
But it misses:
- checking if it was in the list already (emit one event two times ... and it gets added two times)
- have pools of "used" and "unused" events - so on "emit" (once?) things become "used" and are reuseable then
