### ISSUE TITLE
NG crashes when AnimImage goes out of scope

### ISSUE THREAD

**Issue by noroads2015** [bmx-ng/brl.mod#71]
Windows, both 32 bit and 64 bit.  When an image loaded with LoadAnimImage() is garbage collected, I get an error "Unhandled Exception:Attempt toindex array element beyond array length"  In the Debug tag, it shows that it crashes in the Function DeleteTex.
Edit:  Seems to only happen with GLMax2D.  Does not happen with D3D9Max2D
```
SuperStrict
Graphics 300,300
'create an image to load and fill with some random pixels
Global pixmap:TPixmap = CreatePixmap(64,64,PF_RGBA8888)
For Local i:Int = 1 To 10000
	WritePixel pixmap, Rand(0,63), Rand(0,63), $FF000000 + Rand(0,$FFFFFF)
Next


Local image:TImage = LoadAnimImage(pixmap,8,8,0,64)
For Local x:Int = 0 To 7
	For Local y:Int = 0 To 7
		DrawImage image,x*8,y*8,x+y*8
	Next
Next
Flip
image = Null
While Not KeyHit(KEY_ESCAPE) And Not AppTerminate()
	GCCollect()
Wend

```

**Comment by woollybah** [comment]
As far as I am aware, the current glmax2d is quite robust now - there were issues previously with the fact that the GC collects in a different thread.

Can you please confirm that your function looks like this, please?

https://github.com/bmx-ng/brl.mod/blob/b1a2b824daa6f330a2da95935772b9b272605b43/glmax2d.mod/glmax2d.bmx#L92-L99

Thanks!

**Comment by noroads2015** [comment]
Updated brl.mod with the latest, rebuilt all modules, still have a problem.

**Comment by woollybah** [comment]
I've tried coming at it from a different direction.
Please let me know if you have any issues with this latest attempt ;-)

**Comment by noroads2015** [comment]
Seems to have done the trick.  Thanks :)
