### ISSUE TITLE
Win32 brl.timer not 64-bit friendly

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/brl.mod#74]
The use of `timeSetEvent` in brl.timer has not been modified to correctly support x64.

Use of DWORD should be DWORD_PTR, for example.

https://github.com/bmx-ng/brl.mod/blob/735558abb4802fe73ea53fecf1ff7b724ce72aa7/timer.mod/timer.win32.c#L20-L36

**Comment by woollybah** [comment]
According to msdn, `timerSetEvent` is deprecated. And one should use CreateTimerQueueTimer instead ( https://msdn.microsoft.com/en-us/library/windows/desktop/ms682485(v=vs.85).aspx )

It may be worth rewriting it if we are going to the trouble of changing it.

**Comment by GWRon** [comment]
When using the new timer thing my "dll using"-program (with the DLL having a timer) results in a "program no longer working"-message.

I see my "timed function" being called two times until this happens.

**Comment by woollybah** [comment]
re: recompiling.
I went through the same process to get it working for mine too. The first time it showed the "two times" calling also, until I rebuilt it.
Then it appeared to be working as expected on my system.

**Comment by GWRon** [comment]
That is a bit odd as I did not have "quick build" enabled (only "quick scan" - but this was active for all tries above, so affected all builds).

But as you said - all recent tries result in a "working" timer on that machine (already backuped the generated files for diff-comparison but ... seems it is not needed).
