### ISSUE TITLE
Fix for 64bit timers introduced bugs

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#75]
The fix in commit 725b438e15270610af090e21a2313ab17e9b395b introduced some bugs which I - for now - cannot narrow down.

As stated in the bah.mod-issue https://github.com/maxmods/bah.mod/issues/64 the commit above lead to issues communicating with my serial devices. So it seems that something is dependend on the timer - and the timer does no longer behave as it did before the commit.

**Comment by GWRon** [comment]
In my code I open up a device connection ... and set timeouts (does fail without timeout too).

Then I write a specific string to the device - and the device should reply with a string. Using the brl.mod _before_ this commit and it works. Using a revision including above's commit and the "serial.ReadString()" returns an empty string in all cases.

**Comment by woollybah** [comment]
I've tweaked it a little. If that still doesn't work, we can look at reverting to using the old timeSetEvent() (with 64-bit fixes).

I don't see anything wrong with using  CreateTimerQueueTimer. At least from my tests, it performs like the old one. Obviously, there's something that's  interfering with your I/O ?

**Comment by woollybah** [comment]
Yeah, I might roll it back and fix for 64-bit, if the "recommended" API isn't working properly.

**Comment by woollybah** [comment]
I've "reverted" the code to use the old API.

**Comment by woollybah** [comment]
Can I close this now?

**Comment by GWRon** [comment]
Except you intent to try to new timer code ...
