### ISSUE TITLE
brl.xml: add support "xmlDoc.readDoc()" (xml from string)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#80]
~~.mxml provides:~~
```
int
mxmlSaveString(mxml_node_t *node, char *buffer, int bufsize,
               mxml_save_cb_t cb);
```

~~Which should allow for a "libxml compatible" way of converting the xmlDoc to a string rather than saving it to a file.~~

**Comment by GWRon** [comment]
Maybe also wrap `mxmlLoadString` to enable a "libxml compatible" `readDoc()` function (aka loading a xml node set from a string).

**Comment by woollybah** [comment]
Have you tried `doc.ToString()` ?

**Comment by GWRon** [comment]
Hmm ... you're right, ToString() exists already.

`readDoc()`  aka "create xml object from string instead of file" would still be a good addition. Possible workaround would be to pass the string to a memory stream and feed that stream to `parseFile(object)` - but as mxml provides a native function I think the module should at least wrap that.

**Comment by GWRon** [comment]
Without having checked the XML output yet - to format a XML (proper indentation - human readability) the library offers to use a specific callback. If that is not that hard to implement (to allow a custom callback - not the indentation on it's own) then it might be a nice idea to have that too ... what do you think? Useless or "nice to have" ?
