### ISSUE TITLE
Investigate formatting options for xml output

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/brl.mod#81]
The default output of mxml is only to line break at column ~80.
Libxml provides the option to "pretty" format the output by adding spaces to provide element indentation, thus making it easier for someone to read.

mxml provides a callback that allows custom formatting. We should determine if this can be used to provide the same "pretty" styling of xml that we get from libxml.
At the same time we should remove (or increase) the line break column.

**Comment by GWRon** [comment]
@ line break column adjustments:

```C
/* Disable wrapping */
mxmlSetWrapMargin(0);
```

**Comment by GWRon** [comment]
WIthout line breaks you still need to break somewhen to avoid a line containing millions of characters (>1mb xml). Depending on the "line handling" you might reach artificial limits - eg 32bit integer handles for the "string position".

-> break after each "closing tag": `<mytag />~n`, `<mytag>bla</mytag>~n`)
I would use some kind of "default" callback utilizing the custom formatting.

Another option is: use the custom formatting - but skip the "indentation" if no "format" is desired - one tag per line. Another easy (but kind of "odd") solution would be to linebreak every X tags - but this is similar arbitrary than wrapping at a given position of a line.

**Comment by woollybah** [comment]
Indeed, I would have preferred a context... but I suppose counting parent is better than nothing :-p

**Comment by woollybah** [comment]
Well, the callback expects a const char *, which is fine you aren't wanting to dynamically create the text. 

The example assumes a fixed format xml file. Whereas we probably want to have a standard indentation policy when using formatting - like what libxml gives us - without having to implement anything ourselves.

Also, if we were going to generate text dynamically, since there's no context we'd need to do it globally (were we to attempt to keep track of it for freeing later), which is a problem for multi-threading use.

I may have to implement the context stuff that michaelrsweet/mxml#106 refers to... :-(

**Comment by woollybah** [comment]
I ended up implementing the callback context stuff, which worked out great :-)
I think the formatting is okay now - 2-space indents.

**Comment by GWRon** [comment]
A tab takes less space ;-)

Good job...
