### ISSUE TITLE
Makedocs fails with "Error reading from stream"?

### ISSUE THREAD

**Issue by olejr** [bmx-ng/brl.mod#82]
Hello!

After updating to latest last night MaxIDE kept asking me to rebuild docs every time I started it.

Kind of irritating, and when looking at the output from rebuild documentation I see :
```
Rebuilding documentation...
Error:No doc path
Error:No doc path
Building: BlitzMax Help
Building: Modules
------ cut some output
Building: BRL.Bank
Building: TBank
Error reading from stream
Process complete
```
So removed all mods except pub and brl.
After digging around a bit, it seem to come frome a commit back at 6 december, when 
_brl.nod/bank.mod/doc/peek*.bmx_ and _brl.nod/bank.mod/doc/poke*.bmx_ was added.
(Some months since I my last update)

Atleast it's working again here after deleting those peek/poke examples.

edit: Still has those two **Error:No doc path** at the top.

edit2: Also examples in brl.mod/pixmap.mod/doc seem to do tha same ting?

**Comment by olejr** [comment]
Yepp, same thing so feel free to close this.

**Comment by woollybah** [comment]
This should be fixed in the latest makedocs.
