### ISSUE TITLE
Addition to empty array of structs causes memory corruption

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/brl.mod#85]
Adding a non-empty array to an empty array appears to cause memory corruption if the element type of that array is a struct.
Compile the following code in debug mode, 64 bit (i haven't tried 32) and keep an eye on the variables displayed by the debugger:
```BlitzMax
SuperStrict
Framework BRL.StandardIO


Local canvas:TCanvas = New TCanvas()
End


Type TCanvas
	
	Field data:Int[]
	Field rects:SRect[]
	
	Method New()
		Local self_:TCanvas = Self ' just because the debugger doesn't show Self for some reason
		
		data = New Int[10] ' create an object and assign it to Self.data
		
		' okay, so let's examine what address Self.data points to
		Local p1:Byte Ptr = Byte Ptr Object data
		Local l1:Long = Long p1
		Local i1:Int = Int p1
		
		DebugStop ' yep, looks fine
		
		rects :+ [New SRect(3, 3, 6, 6)] ' and now we add something to the empty struct array
		
		Local p2:Byte Ptr = Byte Ptr Object data
		Local l2:Long = Long p2
		Local i2:Int = Int p2
		
		DebugStop ' uh oh
		
		Local data2:Int[] = data ' and boom (goes the debugger)
		
		DebugStop
		
	End Method
	
End Type


Struct SRect ' <- if this is changed to a Type, everything works fine
	
	Field ReadOnly x1:Int
	Field ReadOnly y1:Int
	Field ReadOnly x2:Int
	Field ReadOnly y2:Int
	
	Method New(x1:Int, y1:Int, x2:Int, y2:Int)
		Self.x1 = x1
		Self.y1 = y1
		Self.x2 = x2 ' <- these two assignments overwrite TCanvas.data
		Self.y2 = y2 ' <- (comment them out and observe the difference in p2, l2 and i2)
	End Method
	
End Struct
```
<br>

This is the debugger output at the second breakpoint on my machine:

![image](https://user-images.githubusercontent.com/7982456/51848139-4dee5700-231d-11e9-9a66-10666caa414c.png)

**Comment by GWRon** [comment]
@HurryStarfish 
If BMX internals fail you might compile your stuff with "GDB" information enabled - and then run the final thing through the GNU Debugger (GDB). That way you can type in "bt" after it crashed and GDB will show you the origin of the crash / the backtrace. So while it might fail within the debugging thing you can traverse back to where it originally failed.
