### ISSUE TITLE
Brl.xml: comments read as node, text nodes not recognized

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#90]
`node.GetChildren()` also returns "nodes" which are comments.

```XML
<?xml version="1.0"?>
<test>
	<resources>
		<spritepack name="packname">
			<url>path/to.png</url>
			<children>
				<!-- comment -->
				<child name="child1" x="0" y="0" />
				<child name="child2" x="0" y="0" />
				<!-- comment2 -->
			</children>
		</spritepack>
	</resources>
</test>
```
Also there is no "libxml"-equivalent for `GetContent()`. If you used `ToString()` then eg. the node "url" is expressed as "&lt;url&gt;path/to.png&lt;/url&gt;" so it contains the node-tags too.

Of course one could manually skip comments by checking the first char of the `ToString()` being "&lt;" and then doing a proper "string.find()" but I think that is rather costly.
Also checking if the "url" node has children - and if not, extract the real string value ... is a bit costly.

Is there an inbuilt bot not yet exposed function or how to achieve the desired functionality?

**Comment by woollybah** [comment]
What output would you expect to get for a GetContent() for the various nodes?

**Comment by GWRon** [comment]
libXML returns "path/to.png" for `GetContent()" of this node: "<url>path/to.png</url>".

I assume libXML recognizes that node as "string containing node".

**Comment by GWRon** [comment]
`GetContent()` of the node "<children>...</children>" contains the complete node block including "<children>...</children". So in that case both libs behave the same.

**Comment by GWRon** [comment]
Even that is not correct.

```Xml
<?xml version="1.0"?>
<test>
	<resources>
		<spritepack name="packname">
			<url>path/to.png</url>
			<url2>path/to.png <b>hihi</b></url2>
			<children>
				<!-- comment -->
				<child name="child1" x="0" y="0" />
				<child name="child2" x="0" y="0" />
				<!-- comment2 -->
			</children>
		</spritepack>
	</resources>
</test>
```
libxml:
```BlitzMax
print helper.FindElementNode(rootNode, "url").ToString()
print helper.FindElementNode(rootNode, "url").GetContent()
print helper.FindElementNode(rootNode, "url2").ToString()
print helper.FindElementNode(rootNode, "url2").GetContent()
```

```
<url>path/to.png</url>
path/to.png
<url2>path/to.png <b>hihi</b></url2>
path/to.png hihi
```
libxml somehow just strips the tags of string-nodes within a string-node.

mxml (only `ToString()` available)
```
<url>path/to.png</url>
<url2>path/to.png <b>hihi</b></url2>
```

**Comment by woollybah** [comment]
So you want a GetContent() which acts like the one in libxml.

**Comment by GWRon** [comment]
To make them compatible I think that would be good

**Comment by GWRon** [comment]
Also... Brl.xml nodes have no GetContent() only ToString()

**Comment by GWRon** [comment]
The library might include some "native" functionality already to create the desired effect - but if not then drop a line and I will create some stuff (which can get refined later). I mean I would write some blitzmax code which manipulates the originally returned string.

**Comment by GWRon** [comment]
I tried to create my own `GetContent()` function - but the string stays "empty":

glue.c
```C
BBString * bmx_mxmlGetContent(mxml_node_t * node) {
	const char *opaquevalue = mxmlGetOpaque(node);
	BBString * s = bbStringFromUTF8String(opaquevalue);
	bbMemFree(opaquevalue);
	return s;
}
```
common.bmx (within extern block):
```BlitzMax
	Function bmx_mxmlGetContent:String(handle:Byte Ptr)
```

xml.bmx (in TNode):
```
	Rem
	bbdoc: Fetches the textual content of a node
	End Rem
	Method getContent:string()
		return bmx_mxmlGetContent(nodePtr)
	End Method
```

Isn't that right?

**Comment by GWRon** [comment]
Seems the url-node is of type "mxml_element" instead of "mxml_opaquevalue" 
`fprintf(stderr, "type %d", mxmlGetType( node ));` prints `type 0`.

**Comment by GWRon** [comment]
Seems I am not allowed to `bbMemFree(opaquevalue);` ;-)

Replacing:
```C
mxml_node_t * bmx_mxmlLoadStream(BBObject * stream) {
	return mxmlLoadStream(NULL, bmx_mxml_stream_read, stream, NULL);
}
...
mxml_node_t * bmx_mxmlLoadString(BBString * txt) {
	if (txt == &bbEmptyString) {
		return NULL;
	}

	struct _string_buf buf = {txt = txt};

	return mxmlLoadStream(NULL, bmx_mxml_string_read, &buf, NULL);
}
```

with
```C
```C
mxml_node_t * bmx_mxmlLoadStream(BBObject * stream) {
	return mxmlLoadStream(NULL, bmx_mxml_stream_read, stream, MXML_OPAQUE_CALLBACK);
}
...
mxml_node_t * bmx_mxmlLoadString(BBString * txt) {
	if (txt == &bbEmptyString) {
		return NULL;
	}

	struct _string_buf buf = {txt = txt};

	return mxmlLoadStream(NULL, bmx_mxml_string_read, &buf, MXML_OPAQUE_CALLBACK);
}
(so the callback becomes "MXML_OPAQUE_CALLBACK") I receive the "value" of the nodes.

Still there is one difference:

mxml:
```
<url>path/to.png</url>
path/to.png
<url2>path/to.png <b>hihi</b></url2>
path/to.png
```

libxml:
```
<url>path/to.png</url>
path/to.png
<url2>path/to.png <b>hihi</b></url2>
path/to.png hihi
```

So libxml retrieves the value of the "&lt;b>" node too while mxml skips it. I think this is nothing you can change with the default functions of the library - might need to append values of potential children too. So "GetContent()" would iterate over potential children too.

**Comment by GWRon** [comment]
My `GetContent()` now looks like this:
```BlitzMax
	Method getContent:string()
		'append children
		local s:string =  bmx_mxmlGetContent(nodePtr)

		Local n:Byte Ptr = bmx_mxmlWalkNext(nodePtr, nodePtr, MXML_DESCEND)
		While n
			If bmx_mxmlGetType(n) = MXML_ELEMENT
				s :+ TxmlNode._create(n).getContent() 'recursive
			End If
			n = bmx_mxmlWalkNext(n, nodePtr, MXML_DESCEND)
		Wend
		return s
	End Method
```
Maybe using a `TStringBuilder` is performing better for bigger elements ?

**Comment by woollybah** [comment]
I've implemented

**Comment by woollybah** [comment]
I've implemented a getContent() based on yours. Thanks.
mxml specifically doesn't differentiate comment nodes. There's not a lot one can do about that, other than add some code to handle/ignore them.

Since brl.xml isn't meant to be a complete replacement for bah.libxml, I'm not sure it needs to appear to be a 100% drop-in replacement.

**Comment by GWRon** [comment]
Yes, think so too - no 100% perfection needed - it now at least works for "normal text nodes" - which should be the case the most often.

**Comment by GWRon** [comment]
Is there a "faster" approach to ignore comments than doing the "slow" string-comparison approach in BlitzMax?
- check if first char is a &lt;
- if so check for string.find("&lt;!--")  = 0
- ... ignore if that is the case

**Comment by woollybah** [comment]
Well, the best situation would be for mxml to use a different type for comment nodes, then everything would "just work".

**Comment by GWRon** [comment]
Just recognized that your "getContent()" function you wrote reads content multiple times.
In a simple try to upgrade "Persistence.mod" to use brl.xml I recognized that eg an integer of value "10" became "1010".

When it tried to deserialize a "field" it uses eg. `fieldNode.GetContent().toInt()`.
The line with the field is `<field name="id" type="int">10</field>`.

Your code:
```BlitzMax
	Method getContent:String()
		Local sb:TStringBuilder = New TStringBuilder()
		sb.Append(bmx_mxmlGetContent(nodePtr))

		Local n:Byte Ptr = bmx_mxmlWalkNext(nodePtr, nodePtr, MXML_DESCEND)
		While n
			If bmx_mxmlGetType(n) = MXML_OPAQUE Then
				sb.Append(bmx_mxmlGetContent(n))
			End If
			n = bmx_mxmlWalkNext(n, nodePtr, MXML_DESCEND)
		Wend

		Return sb.ToString()
	End Method
```
finds an "MXML_OPAQUE" node with the very same value already added before the while-loop. This node it found has no name. 

Usingg the method I proposed (adjusted to use TStringBuilder):
```BlitzMax
	Method getContent:String()
		Local sb:TStringBuilder = New TStringBuilder()
		sb.Append(bmx_mxmlGetContent(nodePtr))

		Local n:Byte Ptr = bmx_mxmlWalkNext(nodePtr, nodePtr, MXML_DESCEND)
		While n
			If bmx_mxmlGetType(n) = MXML_ELEMENT Then
				sb.Append(bmx_mxmlGetContent(n))
			End If
			n = bmx_mxmlWalkNext(n, nodePtr, MXML_DESCEND)
		Wend

		Return sb.ToString()
	End Method
```
it correctly reads the "id" (in that case) correct as "10" instead of "1010".

**Comment by woollybah** [comment]
I've just committed something to `pub.mxml` which adds a new comment node type, allowing things like getChildren() to skip over comment nodes - so you end up with similar results to libxml.

**Comment by GWRon** [comment]
That is pretty cool...but adjustments to the wrapped library always mean you need to have luck with merges...or require manual porting changes to new revisions.

Will check your commit later this day

**Comment by GWRon** [comment]
Works.
